"""Normalized language extraction contracts, registry, and shared helpers.

Architectural boundary: extractors return immutable :class:`FileExtraction`
records only. They must not open SQLite, mutate snapshots, call LLMs, or know
about Murder agents / ``/compact``. Persistence mapping lives in
``murder.context_compiler.indexing.mapper``.
"""

from __future__ import annotations

from murder.context_compiler.extraction.common import (
    EXTRACTION_SCHEMA_VERSION,
    DiagnosticAccumulator,
    assign_disambiguators,
    assign_parents_by_enclosure,
    build_extractor_version,
    build_qualified_name,
    derive_contains_relationships,
    disambiguator_from_metadata,
    empty_file_extraction,
    find_enclosing_unit,
    inclusive_range,
    is_exported_hint,
    is_public_python_name,
    make_local_id,
    make_logical_key,
    normalize_signature,
    unit_contains_line,
)
from murder.context_compiler.extraction.models import (
    IMPORT_DEFAULT,
    IMPORT_DYNAMIC,
    IMPORT_MODULE,
    IMPORT_NAMED,
    IMPORT_NAMESPACE,
    IMPORT_RESOURCE,
    IMPORT_SIDE_EFFECT,
    IMPORT_TYPE_ONLY,
    REL_CALLS,
    REL_CONFIGURED_BY,
    REL_CONTAINS,
    REL_EXPORTS,
    REL_IMPLEMENTS,
    REL_IMPORTS,
    REL_INHERITS,
    REL_REFERENCES,
    REL_RENDERS_COMPONENT,
    REL_STYLE_OF,
    REL_TEMPLATE_OF,
    REL_TESTS,
    RESOURCE_ASSET,
    RESOURCE_GENERATED,
    RESOURCE_STYLE,
    RESOURCE_TEMPLATE,
    DiagnosticSeverity,
    ExtractedImport,
    ExtractedReference,
    ExtractedRelationship,
    ExtractedResourceLink,
    ExtractedSemanticUnit,
    ExtractionDiagnostic,
    FileExtraction,
    ImportKind,
    ParseStatus,
    ReferenceKind,
    RelationKind,
    ResourceKind,
)
from murder.context_compiler.extraction.protocols import (
    FrameworkEnricher,
    LanguageExtractor,
)
from murder.context_compiler.extraction.python_ast import (
    EXTRACTOR_ID as PYTHON_EXTRACTOR_ID,
)
from murder.context_compiler.extraction.python_ast import (
    EXTRACTOR_VERSION as PYTHON_EXTRACTOR_VERSION,
)
from murder.context_compiler.extraction.python_ast import (
    PythonAstExtractor,
    module_qualifier_from_path,
    register_python_extractor,
)
from murder.context_compiler.extraction.registry import (
    EXTENSION_TO_LANGUAGE,
    LANG_C,
    LANG_CPP,
    LANG_CSS,
    LANG_GO,
    LANG_HTML,
    LANG_JAVASCRIPT,
    LANG_JSX,
    LANG_PYTHON,
    LANG_RUST,
    LANG_SVELTE,
    LANG_TSX,
    LANG_TYPESCRIPT,
    LANG_VUE,
    LANGUAGE_HINT_ALIASES,
    ExtractionPipeline,
    ExtractorRegistry,
    default_registry,
    reset_default_registry,
)

__all__ = [
    "EXTENSION_TO_LANGUAGE",
    "EXTRACTION_SCHEMA_VERSION",
    "IMPORT_DEFAULT",
    "IMPORT_DYNAMIC",
    "IMPORT_MODULE",
    "IMPORT_NAMED",
    "IMPORT_NAMESPACE",
    "IMPORT_RESOURCE",
    "IMPORT_SIDE_EFFECT",
    "IMPORT_TYPE_ONLY",
    "LANGUAGE_HINT_ALIASES",
    "LANG_C",
    "LANG_CPP",
    "LANG_CSS",
    "LANG_GO",
    "LANG_HTML",
    "LANG_JAVASCRIPT",
    "LANG_JSX",
    "LANG_PYTHON",
    "LANG_RUST",
    "LANG_SVELTE",
    "LANG_TSX",
    "LANG_TYPESCRIPT",
    "LANG_VUE",
    "REL_CALLS",
    "REL_CONFIGURED_BY",
    "REL_CONTAINS",
    "REL_EXPORTS",
    "REL_IMPLEMENTS",
    "REL_IMPORTS",
    "REL_INHERITS",
    "REL_REFERENCES",
    "REL_RENDERS_COMPONENT",
    "REL_STYLE_OF",
    "REL_TEMPLATE_OF",
    "REL_TESTS",
    "RESOURCE_ASSET",
    "RESOURCE_GENERATED",
    "RESOURCE_STYLE",
    "RESOURCE_TEMPLATE",
    "DiagnosticAccumulator",
    "DiagnosticSeverity",
    "ExtractedImport",
    "ExtractedReference",
    "ExtractedRelationship",
    "ExtractedResourceLink",
    "ExtractedSemanticUnit",
    "ExtractionDiagnostic",
    "ExtractionPipeline",
    "ExtractorRegistry",
    "FileExtraction",
    "FrameworkEnricher",
    "ImportKind",
    "LanguageExtractor",
    "ParseStatus",
    "PYTHON_EXTRACTOR_ID",
    "PYTHON_EXTRACTOR_VERSION",
    "PythonAstExtractor",
    "ReferenceKind",
    "RelationKind",
    "ResourceKind",
    "assign_disambiguators",
    "assign_parents_by_enclosure",
    "build_extractor_version",
    "build_qualified_name",
    "default_registry",
    "derive_contains_relationships",
    "disambiguator_from_metadata",
    "empty_file_extraction",
    "find_enclosing_unit",
    "inclusive_range",
    "is_exported_hint",
    "is_public_python_name",
    "make_local_id",
    "make_logical_key",
    "module_qualifier_from_path",
    "normalize_signature",
    "register_python_extractor",
    "reset_default_registry",
    "unit_contains_line",
]
