"""Generate the TypeScript application-protocol contract from Pydantic models."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from enum import Enum
from pathlib import Path

from pydantic import TypeAdapter

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from murder.app.protocol.common import (  # noqa: E402
    APPLICATION_PROTOCOL_VERSION,
    ClientKind,
    ErrorCode,
)
from murder.app.protocol.requests import (  # noqa: E402
    CommandName,
    OrchestrationAction,
    QueryName,
)
from murder.app.protocol.subscriptions import (  # noqa: E402
    NotificationChannel,
    ProjectionTopic,
)
from murder.app.protocol.wire import ApplicationWireMessage  # noqa: E402

OUTPUT = ROOT / "inktui" / "src" / "generated" / "applicationProtocol.ts"


def _union(enum: type[Enum]) -> str:
    return " | ".join(json.dumps(member.value) for member in enum)


def render() -> str:
    schema = TypeAdapter(ApplicationWireMessage).json_schema()
    digest = hashlib.sha256(
        json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    return f"""/* eslint-disable */
// GENERATED by tools/generate_application_protocol.py. DO NOT EDIT.
// Pydantic application-wire schema sha256: {digest}

export const APPLICATION_PROTOCOL_VERSION = {APPLICATION_PROTOCOL_VERSION} as const;

export type ClientKind = {_union(ClientKind)};
export type ErrorCode = {_union(ErrorCode)};
export type QueryName = {_union(QueryName)};
export type CommandName = {_union(CommandName)};
export type OrchestrationAction = {_union(OrchestrationAction)};
export type ProjectionTopic = {_union(ProjectionTopic)};
export type NotificationChannel = {_union(NotificationChannel)};

export interface ClientHello {{
  readonly op: 'client.hello';
  readonly protocol_version: number;
  readonly client: {{ readonly client_id: string; readonly kind: ClientKind }};
}}

export interface ServerHello {{
  readonly op: 'server.hello';
  readonly protocol_version: number;
  readonly server_id: string;
  readonly queries: readonly QueryName[];
  readonly commands: readonly CommandName[];
  readonly subscriptions: readonly ('projections' | 'notifications')[];
  readonly terminal_streams: boolean;
}}

export type ApplicationRequest =
  | {{ readonly kind: 'query'; readonly name: QueryName; readonly params: Record<string, unknown> }}
  | {{ readonly kind: 'command'; readonly name: CommandName;
       readonly params: Record<string, unknown> }};

export interface RequestMessage {{
  readonly op: 'request';
  readonly request_id: string;
  readonly request: ApplicationRequest;
  readonly timeout_s: number;
}}

export interface ReplyMessage {{
  readonly op: 'reply';
  readonly request_id: string;
  readonly result: Record<string, unknown>;
}}

export type SubscriptionSpec =
  | {{
      readonly kind: 'projections';
      readonly topics: readonly ProjectionTopic[];
      readonly cursor?: number | null;
    }}
  | {{
      readonly kind: 'notifications';
      readonly channels: readonly NotificationChannel[];
      readonly cursor?: number | null;
    }};

export interface SubscribeMessage {{
  readonly op: 'subscribe';
  readonly subscription_id: string;
  readonly subscription: SubscriptionSpec;
}}

export interface UnsubscribeMessage {{
  readonly op: 'unsubscribe';
  readonly subscription_id: string;
}}

export interface SubscriptionSnapshot {{
  readonly snapshots: Record<string, Record<string, unknown>>;
  readonly cursor: number;
  readonly mode: 'cold' | 'resume' | 'snapshot_fallback';
  readonly replay: readonly {{
    readonly cursor: number;
    readonly payload: Record<string, unknown>
  }}[];
}}

export interface SubscriptionReadyMessage {{
  readonly op: 'subscription.ready';
  readonly subscription_id: string;
  readonly snapshot: SubscriptionSnapshot;
}}

export interface SubscriptionEventMessage {{
  readonly op: 'subscription.event';
  readonly subscription_id: string;
  readonly cursor?: number | null;
  readonly payload: Record<string, unknown>;
}}

export interface TerminalAttachMessage {{
  readonly op: 'terminal.attach';
  readonly stream_id: string;
  readonly target: {{ readonly session_id?: string | null }};
}}

export interface TerminalDetachMessage {{
  readonly op: 'terminal.detach';
  readonly stream_id: string;
}}

export interface TerminalAttachedMessage {{
  readonly op: 'terminal.attached';
  readonly stream_id: string;
  readonly mode: 'replace';
}}

export interface TerminalFrameMessage {{
  readonly op: 'terminal.frame';
  readonly stream_id: string;
  readonly frame: {{
    readonly mode: 'replace';
    readonly sequence: number;
    readonly session_id: string;
    readonly frame: string;
  }};
}}

export interface ErrorMessage {{
  readonly op: 'error';
  readonly request_id?: string | null;
  readonly subscription_id?: string | null;
  readonly stream_id?: string | null;
  readonly error: {{
    readonly code: ErrorCode;
    readonly message: string;
    readonly details: Record<string, unknown>;
  }};
}}

export type ClientMessage =
  | ClientHello
  | RequestMessage
  | SubscribeMessage
  | UnsubscribeMessage
  | TerminalAttachMessage
  | TerminalDetachMessage;

export type ServerMessage =
  | ServerHello
  | ReplyMessage
  | SubscriptionReadyMessage
  | SubscriptionEventMessage
  | TerminalAttachedMessage
  | TerminalFrameMessage
  | ErrorMessage;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
