/**
 * Per-snapshot cross-language field-shape contract tests for the read-reply DTOs (A-D2 / B-D5).
 *
 * Each Ink slice declares a TypeScript interface that hand-mirrors a Python dataclass in
 * `murder/app/service/client_api.py` with no schema check at the seam — so a rename/type change on
 * either side drifts silently (the plans-panel blank-out, sweep Finding 4, was exactly this).
 *
 * This test pins the Ink CONSUMERS against committed goldens produced by the REAL Python producer
 * serializer (`dto_to_wire` + the `{ok, value}` read envelope), generated by
 * `tests/unit/test_read_reply_dto_goldens.py`. It is the same pattern as the `conversation.block`
 * golden anchor (F11 H3, `conversationBlockContract.test.ts`), extended to the read-reply DTOs.
 *
 * Each golden is the FULL post-envelope wire shape `{ ok: true, value: <DTO> }`. We stub the bare
 * `value` (FakeBusClient re-wraps `state.*` reads in `{ok, value}` and runs the SAME shared unwrap
 * the live `UdsBusClient` runs, A-D3) — so this also exercises the live wrap/unwrap round-trip and
 * keeps the fake honest against the real wire shape.
 *
 * Drift detection:
 *  - Python side: if `dto_to_wire`'s keys/types change, the Python golden test fails (golden no
 *    longer matches the real producer) — forcing a deliberate regenerate.
 *  - Ink side: if a consumer reads a key the producer doesn't emit (renamed/removed field), the
 *    projected row/frontmatter below loses its value → this fails.
 *
 * Complements (does NOT duplicate) `tests/unit/test_protocol_agreement.py` (PROTOCOL_VERSION /
 * Entity / BusEvent names) — that is the protocol layer; this is the per-DTO field-shape layer.
 */

import { describe, expect, it } from 'vitest';
import { FakeBusClient } from '../../src/bus/FakeBusClient.js';
import type { NotesSnapshotReply } from '../../src/store/notes/notesActions.js';
import type { PlansSnapshotReply } from '../../src/store/plans/plansActions.js';
import type { ReportsSnapshotReply } from '../../src/store/reports/reportsActions.js';
import type { CrowSnapshotReply } from '../../src/store/roster/rosterActions.js';
import { createAppStore } from '../../src/store/store.js';
import type { TicketDetailReply } from '../../src/store/ticketDetail/ticketDetailActions.js';
import type { ScheduleSnapshotReply } from '../../src/store/tickets/ticketsActions.js';

import crowGolden from '../fixtures/read-reply-goldens/crow-snapshot.json' with { type: 'json' };
import notesGolden from '../fixtures/read-reply-goldens/notes-snapshot.json' with { type: 'json' };
import plansGolden from '../fixtures/read-reply-goldens/plans-snapshot.json' with { type: 'json' };
import reportsGolden from '../fixtures/read-reply-goldens/reports-snapshot.json' with {
  type: 'json',
};
import scheduleGolden from '../fixtures/read-reply-goldens/schedule-snapshot.json' with {
  type: 'json',
};
import ticketDetailGolden from '../fixtures/read-reply-goldens/ticket-detail.json' with {
  type: 'json',
};

/** The committed golden is the full read envelope `{ ok, value }`; `value` is the bare DTO. */
interface ReadEnvelope<T> {
  ok: boolean;
  value: T;
}

const crow = crowGolden as ReadEnvelope<CrowSnapshotReply>;
const plans = plansGolden as ReadEnvelope<PlansSnapshotReply>;
const notes = notesGolden as ReadEnvelope<NotesSnapshotReply>;
const reports = reportsGolden as ReadEnvelope<ReportsSnapshotReply>;
const schedule = scheduleGolden as ReadEnvelope<ScheduleSnapshotReply>;
const ticketDetail = ticketDetailGolden as ReadEnvelope<TicketDetailReply>;

/** All goldens must be the post-envelope wire shape — the honesty check vs. FakeBusClient. */
function expectEnvelope(env: ReadEnvelope<unknown>): void {
  expect(env.ok).toBe(true);
  expect(env).toHaveProperty('value');
}

/** Build a store with every `state.*` read stubbed by its golden `value` (FakeBusClient re-wraps
 * `state.*` into `{ok, value}` and unwraps via the shared util, mirroring the live transport). */
function setup() {
  const fake = new FakeBusClient();
  // Stub the bare DTO (golden `value`); the fake adds the {ok, value} envelope for `state.*`.
  fake.stubQuery('roster.get', crow.value);
  fake.stubQuery('plans.list', plans.value);
  fake.stubQuery('notes.list', notes.value);
  fake.stubQuery('reports.list', reports.value);
  fake.stubQuery('schedule.get', schedule.value);
  fake.stubQuery('ticket.get', ticketDetail.value);
  const { store, dispose } = createAppStore(fake);
  return { fake, store, dispose };
}

describe('read-reply DTO cross-language field-shape goldens (A-D2)', () => {
  it('every golden is the real {ok, value} read envelope (FakeBusClient live-wrap honesty)', () => {
    expectEnvelope(crow);
    expectEnvelope(plans);
    expectEnvelope(notes);
    expectEnvelope(reports);
    expectEnvelope(schedule);
    expectEnvelope(ticketDetail);
  });

  it('CrowSessionSummary → roster: rich fields project from the real wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.roster.refresh();
    const rows = store.getState().roster.rows;
    expect(rows).toHaveLength(2);
    const crow7 = rows.find((r) => r.agentId === 'crow-7');
    expect(crow7?.role).toBe('crow');
    expect(crow7?.ticketId).toBe('T-101');
    expect(crow7?.ticketTitle).toBe('Wire the detail pane');
    expect(crow7?.status).toBe('running');
    expect(crow7?.lastSeen).toBe('2026-06-09T12:30:00');
    expect(crow7?.openEscalations).toBe(2);
    expect(crow7?.maxSeverity).toBe(3);
    // Nullable columns round-trip as null (defaults applied where Python sent null/absent).
    const planner = rows.find((r) => r.agentId === 'planner-1');
    expect(planner?.ticketId).toBeNull();
    expect(planner?.lastSeen).toBeNull();
    expect(planner?.openEscalations).toBe(0);
    expect(planner?.maxSeverity).toBe(0);
    dispose();
  });

  it('PlanSummary → plans: name/char_count/updated_at/parent project from the real wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.plans.refresh();
    const rows = store.getState().plans.rows;
    expect(rows).toHaveLength(2);
    const root = rows.find((r) => r.name === 'root-plan');
    expect(root?.charCount).toBe(4096);
    expect(root?.updatedAt).toBe('2026-06-09T12:30:00');
    expect(root?.parent).toBeNull();
    const child = rows.find((r) => r.name === 'child-plan');
    expect(child?.parent).toBe('root-plan');
    expect(child?.charCount).toBe(512);
    dispose();
  });

  it('NoteSummary → notes: name/char_count/updated_at project from the real wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.notes.refresh();
    const rows = store.getState().notes.rows;
    expect(rows).toHaveLength(1);
    expect(rows[0]?.name).toBe('design-notes');
    expect(rows[0]?.charCount).toBe(2048);
    expect(rows[0]?.updatedAt).toBe('2026-06-09T12:30:00');
    dispose();
  });

  it('ReportSummary → reports: name/char_count/updated_at project from the real wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.reports.refresh();
    const rows = store.getState().reports.rows;
    expect(rows).toHaveLength(1);
    expect(rows[0]?.name).toBe('review-report');
    expect(rows[0]?.charCount).toBe(1024);
    expect(rows[0]?.updatedAt).toBe('2026-06-09T12:30:00');
    dispose();
  });

  it('ScheduleTicketRow → tickets: row fields project from the real schedule wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.tickets.refresh();
    const rows = store.getState().tickets.rows;
    expect(rows).toHaveLength(1);
    expect(rows[0]?.id).toBe('T-101');
    expect(rows[0]?.title).toBe('Wire the detail pane');
    expect(rows[0]?.status).toBe('in_progress');
    expect(rows[0]?.lastUpdateAt).toBe('2026-06-09T12:30:00');
    expect(rows[0]?.lastUpdateLabel).toBe('2m ago');
    expect(rows[0]?.harness).toBe('cc');
    expect(rows[0]?.model).toBe('opus');
    expect(rows[0]?.pendingDepIds).toEqual(['T-100']);
    expect(rows[0]?.scheduleAt).toBeNull();
    expect(rows[0]?.parent).toBeNull();
    dispose();
  });

  it('UsageGaugeSummary → usage: gauge fields project from the embedded schedule wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.usage.refresh();
    const rows = store.getState().usage.rows;
    expect(rows).toHaveLength(1);
    expect(rows[0]?.harness).toBe('cc');
    dispose();
  });

  it('TicketDetailSnapshot → ticketDetail: status/deps/schedule_at/body project from the real wire shape', async () => {
    const { store, dispose } = setup();
    await store.getState().actions.ticketDetail.open('T-101');
    const detail = store.getState().ticketDetail;
    expect(detail.status).toBe('ready');
    expect(detail.ticketId).toBe('T-101');
    expect(detail.savedBody).toBe(ticketDetail.value.body);
    const fm = detail.frontmatter;
    expect(fm?.title).toBe('Wire the detail pane');
    expect(fm?.status).toBe('in_progress');
    expect(fm?.deps).toBe('T-100, T-099');
    expect(fm?.harness).toBe('cc');
    expect(fm?.model).toBe('opus');
    expect(fm?.worktree).toBe('/wt/t-101');
    expect(fm?.scheduleAt).toBeNull();
    dispose();
  });
});
